In [1]:
import math
import pandas as pd
import numpy as np

In [8]:
# load node to create adjendancy matrix
nodes = pd.read_csv('data/nodes.csv')
nodes.head()

id        lat         lon
0   1  10.767698  106.674405
1   2  10.765503  106.681711
2   3  10.762257  106.676478
3   4  10.756249  106.666372
4   5  10.760359  106.677122

In [29]:
nodemap = {}
for index, row in nodes.iterrows():
    # print(row['lat'], row['lon'], index)
    nodemap[str(round(row['id']))] = [row['lat'], row['lon']]
print(nodemap)

{'1': [10.767697936760957, 106.67440457081288], '2': [10.765502988216346, 106.68171090816944], '3': [10.762256648455452, 106.67647823898406], '4': [10.756248719669571, 106.66637167541596], '5': [10.76035942071941, 106.67712196914763], '6': [10.75751355673015, 106.67413935272307], '7': [10.761171014045628, 106.67501911727996], '8': [10.759885111919823, 106.66900024025054], '9': [10.76765346503475, 106.66712269394012], '10': [10.763911765883876, 106.66002020446868], '11': [10.762256971443463, 106.65708050338836], '12': [10.770383295097414, 106.65809974281402], '13': [10.75539527465039, 106.6624556502542], '14': [10.776475259064204, 106.66354999153228], '15': [10.780764855228592, 106.65876493064972], '16': [10.777950802726458, 106.65621146766752], '17': [10.75889, 106.67766], '18': [10.777877025715137, 106.66560992805572], '19': [10.769740364375355, 106.67074904052824], '20': [10.770844096190466, 106.67314461089975], '21': [10.77672525861494, 106.6837768874348], '22': [10.777838880769757,

In [14]:
edges = pd.read_csv('data/edges.csv')
edges.head()

id  from  to   dis
0   0     1   2   835
1   1     1   3   646
2   2     1   8  1050
3   3     4   8   496
4   4     2   5   761

In [16]:
aM = np.zeros((len(nodemap)+2, len(nodemap)+2))
for index, row in edges.iterrows():
    aM[row['from']][row['to']] = row['dis']
    aM[row['to']][row['from']] = row['dis']
print(aM)

[[  0.   0.   0. ...   0.   0.   0.]
 [  0.   0. 835. ...   0.   0.   0.]
 [  0. 835.   0. ...   0.   0.   0.]
 ...
 [  0.   0.   0. ...   0.  54.   0.]
 [  0.   0.   0. ...  54.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]]


In [17]:
print('adjency matrix is ready')

adjency matrix is ready


In [25]:
from algorithms import dijsktra, bellman_ford, floyd_warshall

start = 15
end = 92

dijsktra.solve_dijsktra(aM, start, end)

bellman_ford.solve_bellman_ford(aM, start, end)

floyd_warshall.solve_floyd_warshall(aM, start, end)

Shortest distance from A to B: 3641.0
Path from A to B: [15, 74, 76, 108, 107, 101, 100, 96, 95, 92]
Shortest distance from A to B: 3641.0
Path from A to B: [15, 74, 76, 108, 107, 101, 100, 96, 95, 92]
Shortest distance from A to B: 3641.0
Path from A to B: [15, 74, 76, 108, 107, 101, 100, 96, 95, 92]


In [24]:
!python main.py 1 2 3

Argument 1: 1
Argument 2: 2
Argument 3: 3
Sum of arguments: 6
